{{- if .Values.ingress.enabled -}}
{{- $fullName := include "go-wiki.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "go-wiki.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts: {{ .Values.ingress.rules.host }}
      secretName: {{ .secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.rules.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
