apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-wiki.fullname" . }}
  labels:
    {{- include "go-wiki.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    {{- include "go-wiki.selectorLabels" . | nindent 4 }}
