resources:
- name: 5m
  type: time
  source: {interval: 5m}
- name: app-source
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-reference-app
    branch: manual-app-deploy
    git_crypt_key: ((ref-secret.ref-key))
jobs:
- name: check-secrets-every-5m
  plan:
  - get: app-source
  - get: 5m
    trigger: true
  - task: check-secrets
    config: 
      platform: linux
      inputs:
        - name: app-source
      image_resource: 
        type: docker-image
        source:
          repository: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/concourse-workers
          tag: worker-demo
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            echo "hello world"
            ls
