version: '3'
services:
  app:
    build:
      context: .
    image: app
    command: ["./django_reference_app/wait_for_postgres.sh", "postgres", "--", "make", "apptest"]
    links:
      - postgres:postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=passw0rd
