apiVersion: skaffold/v1
kind: Config
metadata:
  name: golang-reference-app
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: json0/go-reference-app
deploy:
  kubectl:
    manifests:
    - deploy/kubectl/dev/*.yaml # Deploys all manifest files in the deploy directory
        
