apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-wiki
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "golang-wiki-cloud-platform-reference-app-green"
    external-dns.alpha.kubernetes.io/aws-weight: "50"
  namespace: cloud-platform-reference-app
spec:
  tls:
  - hosts:
    - cp-reference-app.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: cp-reference-app.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: golang-wiki
            port: 
              number: 8082

