apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "django-demo-app.fullname" . }}
  labels:
    app: {{ template "django-demo-app.name" . }}
    chart: {{ template "django-demo-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "django-demo-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "django-demo-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagepullPolicy }}
          ports:
            - name: app-cont-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.name }}
                  key: {{ .Values.env.data.accesskey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.name }}
                  key: {{ .Values.env.data.secretkey }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          resources:       
{{ toYaml .Values.resources | indent 12 }}
