apiVersion: v1
kind: Service
metadata:
  name: golang-wiki
  namespace: cloud-platform-reference-app
  labels:
    app: golang-wiki
spec:
  ports:
  - port: 4000
    name: http
    targetPort: 8082
  selector:
    app: golang-wiki
