apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-wiki
  namespace: cloud-platform-reference-app
spec:
  selector:
    matchLabels:
      app: golang-wiki
  replicas: 3
  template:
    metadata:
      labels:
        app: golang-wiki
    spec:
      containers:
      - name: golang-wiki
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/cloud-platform-reference-app-ecr:latest
        ports:
        - containerPort: 8082
