apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: golang-wiki
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: dns-live
    external-dns.alpha.kubernetes.io/aws-weight: "50"
  namespace: cloud-platform-reference-app
spec:
  tls:
  - hosts:
    - cp-reference-app.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: cp-reference-app.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: golang-wiki
          servicePort: 8082

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: golang-wiki-main
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: dns-live
    external-dns.alpha.kubernetes.io/aws-weight: "50"
  namespace: cloud-platform-reference-app
spec:
  tls:
  - hosts:
    - refapp.cloud-platform.service.justice.gov.uk
    secretName: ref-app-ssl
  rules:
  - host: refapp.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: golang-wiki
          servicePort: 8082

