apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "django-app.fullname" . }}-cronjob-{{ randAlphaNum 5 | lower }}
spec:
  schedule: '0 */6 * * *'
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
          - name: {{ template "django-app.fullname" . }}-cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/bash","-c","python3 manage.py check || exit 1"]
            env:
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ template "django-app.fullname" . }}
                    key: postgresUser

              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ template "django-app.fullname" . }}
                    key: secretKey

              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "django-app.fullname" . }}
                    key: postgresPassword
                  
              - name: POSTGRES_HOST
                value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}

          restartPolicy: Never

