apiVersion: skaffold/v1
kind: Config
metadata:
  name: golang-reference-app

profiles:
  - name: development
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:development"
      artifacts:
      - image: json0/go-reference-app
    deploy:
      kubectl:
        manifests:
        - deploy/kubectl/dev/*.yaml # Deploys all manifest files in the deploy directory
          
  - name: staging
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:staging"
      artifacts:
      - image: json0/go-reference-app
    deploy:
      kubectl:
        manifests:
        - deploy/kubectl/staging/*.yaml # Deploys all manifest files in the deploy directory

  - name: production
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:production"
      artifacts:
      - image: json0/go-reference-app
    deploy:
      kubectl:
        manifests:
        - deploy/kubectl/production/*.yaml # Deploys all manifest files in the deploy directory

  - name: kubectl
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
      - image: json0/go-reference-app
    deploy:
      statusCheckDeadlineSeconds: 300 # Checks the deployment health using the kubectl rollout status
      kubectl:
        manifests:
        - deploy/kubectl/*.yaml # Deploys all manifest files in the deploy directory

  - name: helm
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: json0/go-reference-app
    test:
      - image: json0/go-reference-app
        structureTests:
          - './structure-test/container-test.yaml'
    deploy:
      helm:
        releases:
        - name: skaffold-helm
          chartPath: deploy
          namespace: jason-lab
          values:
            image: json0/go-reference-app
            ingress.rules.host: helm-skaffold.apps.live-1.cloud-platform.service.justice.gov.uk
