nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: demo.apps.cloud-platforms-test.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: django-service
          servicePort: 8000
