apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-demo-app
  labels:
    app: django-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-demo-app
  template:
    metadata:
      labels:
        app: django-demo-app
    spec:
      containers:
        - name: django-demo-container
          image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cloud-platform-reference-app:django
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: demosecret
                  key: thekey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demosecret
                  key: thesecret
